message(STATUS "Loading cmake module: FreeImage")
include(${CMAKE_MODULE_FREEIMAGE_DIR}/FreeImageConfig.cmake)
if(NOT DEFINED AURORAFW_IS_BUILDING)
	find_package(FreeImage)
ENDIF()
install(FILES ${CMAKE_MODULE_FREEIMAGE_DIR}/FreeImageConfig.cmake DESTINATION share/cmake/FreeImage )